apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: fqv97wrsv-python 
  janus-idp.io/tekton: fqv97wrsv-python
  backstage.io/kubernetes-id: fqv97wrsv-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fqv97wrsv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml